#!/bin/zsh
# Making a script that creates new folder for a new week.

# MODIFY THE FOLLOWING FOR EASIER USAGE !
DSApath=~/Documents/Computer\ Science/DSA
OOPpath=~/Documents/Computer\ Science/OOP
MATHpath=~/Documents/Computer\ Science/M\&L/Maths
LOGICpath=~/Documents/Computer\ Science/M\&L/Logic

#for PATHcheck, must be complete path from root, can't use ~ abreviation
PATHcheck="/Users/biaishugo/Documents/Computer Science/DSA/Week"

# Get user input
echo "What week are you starting ?"
read WEEKNUMBER

# If condition to check if file of Week N already exist in DSA folder
# Don't need to check for all folders since if one created, the others also !
if [ -d "$PATHcheck $WEEKNUMBER" ];
then
    # Output if folder already exists
    echo "ERROR --> directory Week $WEEKNUMBER already exists !"
else
    cd $DSApath
    mkdir "Week $WEEKNUMBER"
    echo "Week $WEEKNUMBER created in /DSA"

    cd $OOPpath
    mkdir "Week ""$WEEKNUMBER"
    echo "Week $WEEKNUMBER created in /OOP"

    cd $MATHpath
    mkdir "Week ""$WEEKNUMBER"
    echo "Week $WEEKNUMBER created in /M&L/Maths"

    cd $LOGICpath
    mkdir "Week ""$WEEKNUMBER"
    echo "Week $WEEKNUMBER created in /M&L/Logic"

    #Success message
	echo "The program executed SUCCESSFULLY !"
fi

